name: CombatLogPlugin
author: YeatIsBetter114,Cooltechno
version: '${project.version}'
main: de.cooltechno.combalog.Main
api-version: '1.20'
commands:
  forbid:
    description: forbid a command while a player is in combat
    usage: /forbid <command>